- name: create ansible user
  user:
    name: ansible
    system: yes


- name: copy sudoer_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
